### ISSUE TITLE
404 on Eden page

### ISSUE THREAD

**Issue by micoloth** [elysiajs/documentation#175]
The file `https://github.com/elysiajs/documentation/blob/main/docs/plugins/overview.md` still links to `https://elysiajs.com/plugins/eden/overview.html`, which is 404. I found `https://elysiajs.com/plugins/eden/overview.html` as the first Google result..

**Comment by autarc** [comment]
The issue is addressed here: https://github.com/elysiajs/documentation/pull/174

**Comment by bogeychan** [comment]
Thanks for reporting this issue. The patch has been merged a while ago (as mentioned above)
