### ISSUE TITLE
error handleing page not found.

### ISSUE THREAD

**Issue by arover** [elysiajs/documentation#208]
link is:
https://elysiajs.com/concept/error-handling.html

**Comment by runyasak** [comment]
Hi, @arover.
I've found some links in the docs that were not updated, especially `concept`.

Is this the topic are you looking for?
**Life Cycle** -> **On Error**

<img width="1552" alt="image" src="https://github.com/elysiajs/documentation/assets/6861191/2cfd0169-80a7-4a54-a129-b5fea5b25b20">

https://elysiajs.com/life-cycle/on-error

**Comment by bogeychan** [comment]
Thanks for reporting this issue. The patch has been merged.
