### ISSUE TITLE
Discord Invite link broken

### ISSUE THREAD

**Issue by UmairJibran** [elysiajs/documentation#251]
<img width="689" alt="Screenshot 2024-01-26 at 1 22 59 AM" src="https://github.com/elysiajs/documentation/assets/43789374/fda35670-5228-495d-ae0d-dc13e642deb1">

**Comment by fecony** [comment]
Hey @UmairJibran let me know where is this link to Discord located?
Our documentation discord link located on top of the page and on other pages looks active

**Comment by UmairJibran** [comment]
in the footer of [introduction](https://elysiajs.com/introduction)
