### ISSUE TITLE
functional callback example error

### ISSUE THREAD

**Issue by k3341095** [elysiajs/documentation#357]
### What is the issue?

![image](https://github.com/user-attachments/assets/6d8fceda-b1ec-4be5-96a5-9cb664659749)

The route should be /counter but it is set to /version.

**Comment by bogeychan** [comment]
Thanks for reporting. This has been fixed in https://github.com/elysiajs/documentation/commit/17aa6d24da497b6ca95a84091b2069269b6216ac
