### ISSUE TITLE
Tutorial: `group` is mixed with `prefix`

### ISSUE THREAD

**Issue by eokic** [elysiajs/documentation#433]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

Both `prefix` and `group` are  used here which produces `/note/note` endpoints

```ts
export const note = new Elysia({ prefix: '/note' }) 
    .decorate('note', new Note())
    .group('/note', (app) =>
        app 
            .get('/', ({ note }) => note.data)
            ....
```

### Where did you find it?

https://elysiajs.com/tutorial#group

**Comment by petertaitl** [comment]
resolved in 5eb1479
