### ISSUE TITLE
openapi version mismatch in swagger documentation

### ISSUE THREAD

**Issue by scarf005** [elysiajs/documentation#57]
![image](https://github.com/elysiajs/documentation/assets/54838975/835f9004-a42b-4368-b8ef-418527ff14e2)

however in the swagger plugin implementation it outputs openapi 3.0

https://github.com/elysiajs/elysia-swagger/blob/642375d00ac11f6d91111358283a4664583e6c89/src/index.ts#L101-L110

https://github.com/elysiajs/elysia-swagger/blob/main/CHANGELOG.md#030-beta0---25-feb-2023

https://elysiajs.com/patterns/creating-documentation.html#route-definitions

i think the documentation is outdated, if so i'll open a PR.

**Comment by SaltyAom** [comment]
Ok, I forgot that we updated to OpenAPI V3 some version ago.

Already fixed, thanks you so much.
